### PR TITLE
Add a page for sponsorship

### PR DESCRIPTION
**Pull request by hcho3**
Goal: create a sustainable mechanism to fund the continuous integration infrastructure (https://xgboost-ci.net).

### CODE REVIEW

**Comment by CodingCat** [comment]
maybe we should also put some logs in github.com/dmlc/xgboost

as users are more used to check xgb project from there

**Comment by hcho3** [comment]
@CodingCat I agree. Can you review it and merge this pull request first?

**Comment by CodingCat** [comment]
looks good to me, but I don't have enough permission to merge

**Comment by hcho3** [comment]
@tqchen Can you review?

**Comment by CodingCat** [comment]
@tqchen can you grant me write permission here?

**Comment by CodingCat** [comment]
maybe also NVIDIA now

**Review by tqchen — APPROVED** [review]

**Comment by hcho3** [comment]
Can someone merge this? I don't have write permission.

**Comment by tqchen** [comment]
@hcho3 you should have write permission now

**Comment by hcho3** [comment]
Thanks!

**Pull request merged**
